name: Build and deploy to Azure

on: [push]

jobs:
  build:
    name: build using
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100
    
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: dotnet publish
        run: dotnet publish -c Release -r win-x86 --self-contained -o myapp
      
      - name: deploy to Azure
        uses: azure/webapps-deploy@v1
        with:
          app-name: mau201910githubactions
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          package: './myapp'
